
[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"

[target.wasm32-unknown-unknown]
linker = "rust-lld.exe"

#[unstable]
#build-std = [
#	"std",
#	"panic_abort",
#	"alloc",
#	"proc_macro",
#	"core",
#]
