name: Rust

on:
  push:
    branches: [ master, nightly ]
  pull_request:
    branches: [ master, nightly ]

env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    
    # Prepares rustup for wasm compiler
    - name: Add wasm-target
      run: rustup target add wasm32-unknown-unknown
      
    # Pulls in git dependencies
    - uses: actions/checkout@v2
    - name: Pull git depends
      run : git submodule update --init --recursive
      
    # Builds wasm setup
    - name: Build
      run : cargo build --release --target wasm32-unknown-unknown
      
    # Prepares node js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    # Loads NPM modules for webpack
    - name: Install NPM depends
      run : npm install

    # Finishes bundle
    - name: Bundle + Build
      run: npm run build
      
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        clean: false
 
    - name: Commit files
      run: |
        git config --local user.email "78537307+FlareFlo@users.noreply.github.com"
        git config --local user.name "FlareFlo"
        git add dist
        git commit -m "Dist - action"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
