name: Rust

on:
  push:
    branches: [ nightly ]
  pull_request:
    branches: [ nightly ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps: # Setting up SSH key
      - name: Get SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_CAVE }}
          known_hosts: 'placeholder'

      # Adding hosts for CD
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.CAVE_IP }} >> ~/.ssh/known_hosts

      # Install the needed rust toolchain
      - name: Add toolchain
        run: rustup toolchain install --profile minimal nightly-x86_64-unknown-linux-gnu

      # Prepares rustup for wasm compiler
      - name: Add wasm-target
        run: rustup target add wasm32-unknown-unknown

      # Pulls in git dependencies
      - uses: actions/checkout@v2
      - name: Pull git depends
        run: git submodule update --init --recursive --remote

      # Prepares node js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Loads NPM modules for webpack
      - name: Install NPM depends
        run: npm install

      # Loads sass from NPM
      - name: Install sass
        run: npm install -g sass

      # Builds wasm setup
      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown

      # Finishes bundle
      - name: Bundle + Build
        run: npm run build

      # Get goatcounter js for self hosting
      - name: Download count.js
        run: wget "https://gc.zgo.at/count.js" -P dist/

      # Create dummy file for successful removal of any file
      - name: Create dummy file
        run: ssh flareflo-github@${{ secrets.CAVE_IP }} 'cd /var/www/nightly_flo_wt_calc; touch placeholder.txt'

      # Clean up dist folder before pushing new set
      - name: Prepare server for rsync
        run: ssh flareflo-github@${{ secrets.CAVE_IP }} 'rm -rf /var/www/nightly_flo_wt_calc/*'

      - name: Deploy with rsync
        run: rsync -avz ./dist/ flareflo-github@${{ secrets.CAVE_IP }}:/var/www/nightly_flo_wt_calc/dist
